### ISSUE TITLE
The default acks of Producer should be 1 than zero

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1549]
```java
  class Builder<Key, Value> implements com.island.ohara.common.Builder<Producer<Key, Value>> {
    private short numberOfAcks = 0;
```

The default acks is zero and it means that we don't want the acknowledgement from any broker. It does not make sense if we want to expose this Producer client to normal developers.

[code link](https://github.com/oharastream/ohara/blob/master/ohara-kafka/src/main/java/com/island/ohara/kafka/Producer.java#L59)

**Comment by dc-tw** [comment]
我有意願參與這個issue

**Comment by chia7712** [comment]
> 我有意願參與這個issue

hi @dc-tw

歡迎來到ohara，如果你已經有PR經驗了，麻煩就準備好PR，我們可愛的jenkins會自動幫你運行相關測試。

如果沒有PR經驗，那以下是一個簡單的步驟：
1. fork ohara到你的帳號底下 （以下稱fork ohara為你的repo)
1. git clone你的repo
1. 在本地使用git切換到一個branch (名稱隨意)
1. 完成修改並commit後git push到你的repo
1. 點選pull Request頁面並發起PR

上述若有不清楚之處，還請提出。

**Comment by dc-tw** [comment]
想請教下, 我在操作4的時候
已經先git commit, 而後因為要push回我的repo時, 發生了權限上的問題

git push後
出現了fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

而後改使用git push -u origin master

To https://github.com/dc-tw/ohara
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/dc-tw/ohara'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

請問這是說我應該先在初始的repo(oharastream的)索取資格嗎?
謝謝

**Comment by dc-tw** [comment]
後來我嘗試了這兩種方法
https://gitbook.tw/chapters/github/fail-to-push.html
git pull --rebase
在git pull有成功但是要使用git push -u origin master
遇到與剛剛相同的錯誤

git push -f
這個則是遇到與操作git push相同的錯誤

**Comment by dc-tw** [comment]
問題是出在 我誤解了開新的branch的意思

**Comment by konekoya** [comment]
Can you show us the output of your `git remove -v`?

**Comment by dc-tw** [comment]
$ git remote -v
origin  https://github.com/dc-tw/ohara (fetch)
origin  https://github.com/dc-tw/ohara (push)

**Comment by chia7712** [comment]
@dc-tw

要麻煩在你本地開一個新branch喔，例如

git checkout -b fix_1549
// 做一些修改
git add - A // 把你的修改加到git 追逐
git commit -m “#1549 ...” // 提交變更到本店repo
git push origin fix_1549 // 提交commit到github

上述完成後 就可以到Pull Request頁面提交PR

**Comment by dc-tw** [comment]
@chia7712 我依照步驟順利建立branch並push
可能我在上一個branch就已經commit過
以致於在新的branch fix 1549沒辦法pr

很抱歉多弄了一個issue 1553

**Comment by vitojeng** [comment]
@dc-tw 沒關係喔. 我猜可能有其他情形沒注意到而導致.
要不要先把 #1550 close, 然後重新進行一次? 
(記得也要把目前的 local/origin branch 一併刪除)

**Comment by vitojeng** [comment]
@dc-tw  另外有一點要注意的，未來可能需要經常與 upstream repo(就是指 [oharastream/ohara](https://github.com/oharastream)) 同步。由於不定時都會有新的 commits 被 merge 到 master，這個時候你的 repo 就會開始逐漸變 "舊"。

因此在你建立新的 branch 時，與 upstream repo 同步一下還蠻需要的喔。

sync 的相關資訊可參考這裡:
> https://gitbook.tw/chapters/github/syncing-a-fork.html
> https://help.github.com/en/articles/syncing-a-fork

**Comment by dc-tw** [comment]
請問我已經rebase之後這個算是完成了吧?
是我少做了什麼所以這個issue沒有關掉嗎

**Comment by chia7712** [comment]
> 請問我已經rebase之後這個算是完成了吧?

要等到你的PR跑過QA後而且被合併才算是完成喔

**Comment by chia7712** [comment]
@dc-tw 感謝貢獻
