### ISSUE TITLE
Stream APIs take multiples from/to topics but the streamapp take them as single from/to topic

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2245]
The problems are shown below.
1. the type of from/to is declared to "string" than "TopicKeys" (related to #2158)
1. stream APIs accepts multiple from/to topics but it does not work actually.

I'm scared by this inconsistency and out-of-control.

- [x] for branch 0.8 (#2264)
  - [x] add missing annotate "test" (#2345)
- [x] for branch 0.7 (#2273)
  - [x] ~add missing annotate "test"~ (Since this fix is not affect normal process, RM doesn't expect to apply this fix to 0.7 version)

**Comment by saivirtue** [comment]
It's for API consistency and flexible.

rather than change to single topic, I'm prefer and some notes in the `StreamApp`

**Comment by chia7712** [comment]
> rather than change to single topic, I'm prefer and some notes in the StreamApp class

The APIs accept the “array” of topics, right?

Does streamapp work well if the form/to topics are defined to multiple topics indeed?

**Comment by saivirtue** [comment]
> Does streamapp works well if the from/to topics are defined to multiple topics indeed?

Unfortunately, no. The original idea to support array of topics in stream is
1. Ohara Manager doesn't need to do a special dynamic form for streamApp since they all accept array topics.
2. If the streamApp **do** support multiple topics, it is backward compatible since we already accept array topics.

But In a foreseeable future, it is still weird for me to accept multiple from/to topics as I explained before that  **Each streamApp only uses one kafkaStreams instance, which means, 1-1 topic pair**
(But still, in a kafka streams application user could use multiple topics like [here](https://stackoverflow.com/a/42492928) and [here](https://stackoverflow.com/a/49458953))

The multiple topics design need a further discussion, and I agree with your point of 
> stream APIs accepts multiple from/to topics but it does not work actually.

At any rate, We can have a quick discussion and make consensus with @oharastream/frontend

**Comment by chia7712** [comment]
> The multiple topics design need a further discussion,

the first guild to design is we can't expose a APIs which can break our services. I'd say this is a critical issue to ohara and we should freeze the release right now. The workaround is not a solution with a explicit bug. By contrast, workaround is a "not-completed" solution with a room to address more advances.

**Comment by saivirtue** [comment]
As discussion, StreamApp should throw exception if from/to topics size is bigger than 1.

Let me take over this issue?

**Comment by chia7712** [comment]
> Let me take over this issue?

feel free to take over it :)

**Comment by chia7712** [comment]
reopen since the new test case (testOnlyAcceptOneTopic) isn't annotated with "@Test"
