### ISSUE TITLE
Add non-technical sentences to catch users

### ISSUE THREAD

**Issue by Wei-1** [oharastream/ohara#2341]
When a potential user is browsing a project, what the user want to see is:
**Can this project help me on my task**

In this regard, Ohara only states that the user can build streaming application at Scale and didn't provide any further information.
It is rather unclear what streaming applications is that statement talking about.
And the README goes on to talk about the technical components, which the user will start to care only after they decide to use the project.

I will recommend putting some use cases with screenshots right at the beginning to help the user understand what can be done with this project, and if they can benefit from using it.

**Comment by chia7712** [comment]
> I will recommend putting some use cases with screenshots right at the beginning to help the user understand what can be done with this project, and if they can benefit from using it.

We are on the same page. In fact, we are writing the introduction of the usage/benefit of/from ohara. But We write it in Chinese and these documentation will be published to Facebook group (https://m.facebook.com/profile.php?id=436792543715893&ref=content_filter), because most ohara users are familiar with Chinese than English.

In short, you suggestions is great for ohara, but it is in queue and we have to address it later.

**Comment by Wei-1** [comment]
I read those FB posts, found that we should move some screenshots to this README,
and that's why I created this issue.

**Comment by chia7712** [comment]
@Wei-1 you are right. Do you have free cycle to address it? Or @konekoya Is it ok to translate the  introduction you write from Chinese to English?

**Comment by Wei-1** [comment]
I can make a PR tomorrow.

**Comment by chia7712** [comment]
@Wei-1 thanks for contribution.

**Comment by vitojeng** [comment]
@Wei-1 It's awesome. thanks for contribution.
