### ISSUE TITLE
The UI checkbox item of FTP-Sink-Connector should not send null

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#2492]
**Describe the bug**
The [write header] checkbox item of FTP-Sink-Connector will send null  on default value.

**To Reproduce**
1. Create v0.7 configurator and manager
2. Gen nodes and workspace and pipeline
3. Add FTP-Sink-Connector and test connection

**Expected behavior**
The UI checkbox item of FTP-Sink-Connector should not send null

**Screenshots**
![螢幕快照 2019-08-29 上午11 54 26（2）](https://user-images.githubusercontent.com/46185836/63909227-7a558780-ca54-11e9-8ba7-a4e7f15a8574.png)

**Operation System (please complete the following information):**
Backend OS & Version: CentOS 7.3
Frontend OS & Version: CentOS 7.3
Browser & Version : Google Chrome , 版本 75.0.3770.100 (正式版本) (64 位元)

**Comment by HarryChiang143** [comment]
Ping @wu87988622 @saivirtue

**Comment by konekoya** [comment]
Thanks for reporting :)

**Comment by chia7712** [comment]
@konekoya would you please give a conclusion?

**Comment by konekoya** [comment]
> @konekoya would you please give a conclusion?

Sure, I will write down the frontend part! But the backend part would need @saivirtue's help as I don't know much about the backend change in this particular issue :)


#### Why this is happening
The default value of the __write header__ definition is `null` but since the valid values for this definition is a `Boolean` value which means the value should either be `ture` or `false`. But right now manager is not handling this and simply return the default `null` value back to the backend, therefore, the error 

#### Conclusion
As the metadata has provided needed information for UI. If a default value cannot be handled in the frontend (e.g. `null`). UI should return a valid value instead of values like `null`

This issue is affected in both 0.7 and the master. So the fix will go into these two branches

/cc RM @wu87988622 @chia7712 @saivirtue @HarryChiang143

**Comment by konekoya** [comment]
@HarryChiang143 this was fixed in #2501. I will update this thread once 0.7.1 is released
