### ISSUE TITLE
nothing is displayed when I tried to add topic to pipeline

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3012]
![註解 2019-10-15 141452](https://user-images.githubusercontent.com/6234750/66804882-39f38f80-ef56-11e9-841c-42d7c34ad37e.png)

**Comment by chia7712** [comment]
@konekoya @wu87988622 please take a look

**Comment by konekoya** [comment]
I can confirm it's indeed a bug and can be reproduced in the current master branch. However, as we discussed today, we will no longer fix bugs in the master branch if a bug only related to UI. We will, however, fix bugs in 0.8.x branch if the bug is severe enough and affected demo scenarios. @chia7712 Thanks for reporting this anyway :)

cc @saivirtue @eechih @wu87988622
