### ISSUE TITLE
the type of default value should be equal to DataType.value

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#3162]
Since the `valueType` could define the actual value data type, we can "convert" the defaultValue to be the "actual" valueType; But the settings are dynamic, user can do what ever they want to do.
For example,
```
{
  "valueType": "INT",
  "defaultValue": "2"
```
The defaultValue should be 2, not be "2".

/cc @wu87988622 @konekoya @chia7712

**Comment by chia7712** [comment]
This is a bit hard to backend since all values of connector definitions are stored in kafka. Unfortunately, kafka is bad at json that it can’t keep the type - all is in json string.

However, as a good APIs provider, the consistency of data type is indeed required. 

I will go back after fixing #3155
