### ISSUE TITLE
[Question] 加入第一個source的時候預設的位置是在toolbox後面(也就是會被擋住)

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3742]
![1](https://user-images.githubusercontent.com/6234750/71946054-9851a680-3203-11ea-818b-3d9c8f229136.jpg)
![2](https://user-images.githubusercontent.com/6234750/71946053-9851a680-3203-11ea-89f3-80ec815c8748.jpg)

**Comment by chia7712** [comment]
FYI @oharastream/frontend

**Comment by saivirtue** [comment]
Do you "drag" the component to paper and "move" your mouse too quickly?
Because we have to call a bunch of requests to create a component, the drag & drop behavior may cause a little delay (topic component may delay more serious...)

**Comment by chia7712** [comment]
> Do you "drag" the component to paper and "move" your mouse too quickly?

I didn't "drag" anything. I just click the connector and then enter the name :(

**Comment by saivirtue** [comment]
I see...
"Click to add" is not what we design for, and we will assume you want to "drag" the component in the current mouse place...
Maybe we could disable the add behavior if the mouse is in toolbox area?
What do you think? @kon

**Comment by konekoya** [comment]
> I didn't "drag" anything. I just click the connector and then enter the name :(

That's because our mouse event is now binding on a click event. And so click down will trigger the "drag" to start and click up will pop open a dialog for entering cell name. Maybe we can check if the mouse actually "moved/dragged" and then open the dialog. 

> Maybe we could disable the add behavior if the mouse is in toolbox area?
What do you think? @konekoya

I've thought about this but not sure if @eechih is okay with decision :)

**Comment by konekoya** [comment]
Tracked and will be addressed in #3815
