### ISSUE TITLE
[Question] 拖拉元件以新增private topics的時候多點一下會跑出多餘的topics

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3763]
步驟:
1. 拖拉"pipeline only"到畫布上
1. 點個幾下
1. 跑出一堆topics

![asdsad](https://user-images.githubusercontent.com/6234750/71956848-2b500800-3227-11ea-8375-600d52c04e28.jpg)

@oharastream/frontend 麻煩確認一下這是否為**預期**的行為

**Comment by konekoya** [comment]
The knows issue here is dragging and dropping a topic from Toolbox is very slow (because we're hitting many API endpoints behind the sense, like "create topic, start topic, update pipeline, etc.") but clicking on the paper adds more topics into the pipeline is very strange. I will look into this. 

Thanks for reporting this!

**Comment by konekoya** [comment]
A dedicate [issue](#3766) is open for this. So i'm closing this issue :)
