### ISSUE TITLE
As a passerby, I hope for Project CI Stability

### ISSUE THREAD

**Issue by Wei-1** [oharastream/ohara#813]
From the recent build history, the 10 most recent merge history in the master branch is 4 successes and 6 fails. (2019-04-18)
Among these 6 fails, only 2 fails have the same error log and all others failed with different reasons.

I wonder if we can implement some retries in the testing to increase the success rate?
Or is there a more robust testing environment that we can implement together with the test.

**Comment by Wei-1** [comment]
Please help to assign, label, or just close the issue as a part of the standard process.

**Comment by konekoya** [comment]
> From the recent build history, the 10 most recent merge history in the master branch is 4 successes and 6 fails. (2019-04-18)

AFAIK, these failed builds were not the usual case. It's due to we were tweaking some jenkins task config

> I wonder if we can implement some retries in the testing to increase the success rate?

Not sure if I understand this correctly. But if you're talking about manaually re-run a CI build for PRs. We already have a few retry commands that you can use to trigger another CI build from each PR. See  https://github.com/oharastream/ohara/blob/master/CONTRIBUTING.md#pull-request-commands

Hope this help :)

**Comment by chia7712** [comment]
> I wonder if we can implement some retries in the testing to increase the success rate?

We don't enable jenkins to retry failed test automatically since it would be better to see "what happen on your tests". As @konekoya mentioned before, we provide a **command** to retry failed module manually if you believe the failure is unrelated to your code.

Please feel free to file issue to stabilize the flaky tests. We all hate unstable tests :)

**Comment by Wei-1** [comment]
> AFAIK, these failed builds were not the usual case. It's due to we were tweaking some jenkins task config

I will close this since the errors are caused by tweaking config.
